version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: pytest
    versions:
    - 6.2.1
